name: Canary

on:
  push:
    branches: [canary]
  pull_request:
    types: [opened, synchronize]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/checkout@v2
        with:
          fetch-depth: 25
      - run: yarn install --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create commit with version number
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com

      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}