name: CI

on:
  push:
    branches: [canary]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@sushiswap'
          cache: 'yarn'
      - run: yarn
      - run: yarn build
      - run: yarn test
